services:
  text-segmentation:
    image: text-segmentation
    container_name: segmentation
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "11434:11434"
